### ISSUE TITLE
Spring support?

### ISSUE THREAD

**Issue by swrobel** [godfat/rib#11]
Rib is awesome! I was wondering if you have any plans to support [spring](https://github.com/rails/spring) when running `rib rails`

**Comment by godfat** [comment]
Thank you!

Personally I don't use Spring (Java always comes to my mind when someone mentioned Spring :x) so I have no plans to support it. However, I would take a look to see if it's easy to integrate it and support it if people (n > 0) are using it. Will let you know how it goes.

On the other hand, pull requests are always welcome.

**Comment by godfat** [comment]
I just tried a bit, it seems pretty straightforward to support it? Can you try if this works for you?

Thanks!

**Comment by swrobel** [comment]
:clap: works perfectly! :100:

**Comment by godfat** [comment]
Will do a release shortly then. Thanks!

**Comment by godfat** [comment]
1.2.91 just released. Have fun.
