### ISSUE TITLE
Can I exit all nested anchor by one command?

### ISSUE THREAD

**Issue by roger35972134** [godfat/rib#13]
Is there a command for exit all nested anchor?
thanks!

**Comment by godfat** [comment]
Sorry for the long wait. Was too busy these days.

Short answer is no, there's no way to do that right now.

Longer answer is that I am still checking if there's a way to do so, and if not, perhaps add something which allow you to do so.

**Comment by roger35972134** [comment]
Anyway, thanks for your answer.
I've been your speech of Ruby*5. It's pretty cool, I'll keep trying RIB haha.

**Comment by godfat** [comment]
@roger35972134 Thanks! I just added `Rib.stop_anchors` to do so. You could try the master branch. If everyone went well, I'll release a new version soon.

**Comment by roger35972134** [comment]
So quick ! Thanks, I'll try it later

**Comment by roger35972134** [comment]
It's running well for me. thanks

**Comment by godfat** [comment]
Thanks for confirming!
