### ISSUE TITLE
Code fails under RIB but works under IRB

### ISSUE THREAD

**Issue by TechRsch** [godfat/rib#14]
I was trying to run some code from [here](https://aaronlasseigne.com/2014/07/20/know-ruby-clone-and-dup/), but it failed with 

```
TypeError: no implicit conversion of Fixnum into String
.../gems/rib-1.5.1/lib/rib/api.rb:100:in `+'
.../gems/rib-1.5.1/lib/rib/api.rb:100:in `format_result'
.../gems/rib-1.5.1/lib/rib/api.rb:82:in `print_result'
.../gems/rib-1.5.1/lib/rib/core/last_value.rb:13:in `print_result'
.../gems/rib-1.5.1/lib/rib/api.rb:41:in `loop_once'
.../gems/rib-1.5.1/lib/rib/core/multiline.rb:75:in `block in loop_once'
.../gems/rib-1.5.1/lib/rib/core/multiline.rb:74:in `catch'
.../gems/rib-1.5.1/lib/rib/core/multiline.rb:74:in `loop_once'
.../gems/rib-1.5.1/lib/rib/core/squeeze_history.rb:21:in `loop_once'
.../gems/rib-1.5.1/lib/rib/api.rb:29:in `block in in_loop'
.../gems/rib-1.5.1/lib/rib/api.rb:29:in `catch'
.../gems/rib-1.5.1/lib/rib/api.rb:29:in `in_loop'
.../gems/rib-1.5.1/lib/rib/shell.rb:51:in `loop'
.../gems/rib-1.5.1/lib/rib/runner.rb:81:in `loop'
.../gems/rib-1.5.1/lib/rib/runner.rb:76:in `run'
.../gems/rib-1.5.1/bin/rib:5:in `<top (required)>'
.../bin/rib:22:in `load'
.../bin/rib:22:in `<main>'

```
Running it under IRB worked as expected.  The code is:
```
class CloneWatcher
  # IRB calls `inspect` but for our example
  # we're interested in knowing `object_id`.
  alias_method :inspect, :object_id

  private

  def initialize_copy(source)
    puts "Copy: #{source.inspect}"
    super
  end

  def initialize_dup(source)
    puts "Dup: #{source.inspect}"
    super
  end

  def initialize_clone(source)
    puts "Clone: #{source.inspect}"
    super
  end
end
cw = CloneWatcher.new

```

**Comment by godfat** [comment]
Inspect should return a String, not a Fixnum. The offending line in your code was:

``` ruby
alias_method :inspect, :object_id
```

`object_id` would return a number rather than a string. You could instead write:

``` ruby
def inspect
  object_id.to_s
end
```

**Comment by TechRsch** [comment]
Okay, yes that does make sense and it does work.  I am curious, though, as to why it works under IRB as originally coded?

**Comment by godfat** [comment]
IRB might be converting the result to string anyway. Something like:

``` ruby
```

**Comment by godfat** [comment]
IRB might be converting the result to string anyway. Something like:

``` ruby
```

**Comment by godfat** [comment]
IRB might be converting the result to string anyway. Something like:

``` ruby
result.inspect.to_s
```

Or maybe it's doing the conversion via:

``` ruby
"#{result_prompt}#{result.inspect}"
```

I think we could probably do the same. However I am thinking that perhaps we should also emit a warning when this happens, as this is clearly a bug in the client code. A warning would be nice.

**Comment by TechRsch** [comment]
Interesting.  Your last comment prompted me to just convert the use of inspect to object_id directly.  When I did that, it worked even without the explicit string conversion.  Thoughts?
```
>> class CloneWatcher
 |   # IRB calls `inspect` but for our example
 |   # we're interested in knowing `object_id`.
 |   #alias_method :inspect, :object_id
 |
 |   private
 |
 |   def initialize_copy(source)
 |     puts "Copy: #{source.object_id}"
 |     super
 |   end
 |
 |   def initialize_dup(source)
 |     puts "Dup: #{source.object_id}"
 |     super
 |   end
 |
 |   def initialize_clone(source)
 |     puts "Clone: #{source.object_id}"
 |     super
 |   end
 | end
=> :initialize_clone
>> cw = CloneWatcher.new
=> #<CloneWatcher:0x33a4670>
>> cw.inspect
=> "#<CloneWatcher:0x33a4670>"
>> dup = cw.dup
Dup: 27075384
Copy: 27075384
=> #<CloneWatcher:0x31d60e8>
>> clone = cw.clone
Clone: 27075384
Copy: 27075384
=> #<CloneWatcher:0x314ce98>
>>
```

**Comment by godfat** [comment]
Not sure what you mean? You should still make sure that inspect would return a string, otherwise not just Rib, other libraries might also break due to this.

If you're asking why `cw.inspect` didn't crash, then it's because it's used like `cw.inspect.inspect`, which would be a string.

**Comment by godfat** [comment]
Oh, I guess you're asking the code in the post.

Well, it really depends on what you want to do. If you're just doing experiments, then both should be fine. The only thing you shouldn't do is returning a number for inspect. Which is definitely wrong.

**Comment by TechRsch** [comment]
I was referring to the puts executed within the initialize_* methods.  When they use inspect, I had to explicitly convert object_id.to_s.  But, when they use object_id, conversion is implicit.  

Okay, got your last comment.  Inspect must return a String.  Got it.  

Thanks.

**Comment by godfat** [comment]
Those are fine. No problems. I'll add some changes to emit a warning when inspect is not returning a string. This would be a least more user friendly.

Thanks for the information!

**Comment by godfat** [comment]
@TechRsch Now it would emit a warning instead of crashing on master. Please try it if you're interested.

**Comment by TechRsch** [comment]
@godfat I'm not getting it.  I even uninstalled rib and installed it again.  Same error.  Is there something else I need to do?

**Comment by godfat** [comment]
I haven't released a new version yet, it's only on master. If you don't
know how to try it, I could notify you when I released a new version.

**Comment by TechRsch** [comment]
No, I can pull it.

**Comment by TechRsch** [comment]
That's great.  I received the warning but it ran successfully, as desired:
`rib: CloneWatcher#inspect is not returning a string`

I did have a problem doing the build and had to pull a couple of lines out of gemspec:
```
projects\rib>gem build rib.gemspec
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
ERROR:  While executing gem ... (Gem::InvalidSpecificationException)
    ["test/extra/test_anchor.rb"] are not files

```
Thanks.

**Comment by godfat** [comment]
Great, thanks for trying.

The gemspec was outdated. You could regenerate it by running `rake gem:spec`.

I updated it at https://github.com/godfat/rib/commit/cee38d88cdb62f04a5259a1254d92b9a6cac03e4
