### ISSUE TITLE
Using backslash line continuation character results in syntax error

### ISSUE THREAD

**Issue by TechRsch** [godfat/rib#15]
I was looking into this site: [A look at how Ruby interprets your code](https://blog.appsignal.com/2017/08/01/ruby-magic-code-interpretation.html).  When I tried their first example which uses a \ to continue a line, I received a SyntaxError.  I tried the same code on IRB and it worked.  The error signal was:

> D:\BitNami\rubystack-2.2.5-3\projects>rib
>> "foo" \\
SyntaxError: (rib):1: syntax error, unexpected $undefined, expecting end-of-input
"foo" \\
       ^
  D:/Bitnami/rubystack-2.2.5-3/ruby/lib/ruby/gems/2.2.0/gems/rib-1.5.1/lib/rib/api.rb:80:in `eval'
  D:/Bitnami/rubystack-2.2.5-3/ruby/lib/ruby/gems/2.2.0/gems/rib-1.5.1/lib/rib/api.rb:80:in `loop_eval'
  D:/Bitnami/rubystack-2.2.5-3/ruby/lib/ruby/gems/2.2.0/gems/rib-1.5.1/lib/rib/core/multiline.rb:84:in `loop_eval'
  D:/Bitnami/rubystack-2.2.5-3/ruby/lib/ruby/gems/2.2.0/gems/rib-1.5.1/lib/rib/api.rb:68:in `eval_input'
  D:/Bitnami/rubystack-2.2.5-3/ruby/lib/ruby/gems/2.2.0/gems/rib-1.5.1/lib/rib/api.rb:39:in `loop_once'
  D:/Bitnami/rubystack-2.2.5-3/ruby/lib/ruby/gems/2.2.0/gems/rib-1.5.1/lib/rib/core/multiline.rb:75:in `block in loop_once'
  D:/Bitnami/rubystack-2.2.5-3/ruby/lib/ruby/gems/2.2.0/gems/rib-1.5.1/lib/rib/core/multiline.rb:74:in `catch'
  D:/Bitnami/rubystack-2.2.5-3/ruby/lib/ruby/gems/2.2.0/gems/rib-1.5.1/lib/rib/core/multiline.rb:74:in `loop_once'
  D:/Bitnami/rubystack-2.2.5-3/ruby/lib/ruby/gems/2.2.0/gems/rib-1.5.1/lib/rib/core/squeeze_history.rb:21:in `loop_once'
  D:/Bitnami/rubystack-2.2.5-3/ruby/lib/ruby/gems/2.2.0/gems/rib-1.5.1/lib/rib/api.rb:30:in `block in in_loop'
  D:/Bitnami/rubystack-2.2.5-3/ruby/lib/ruby/gems/2.2.0/gems/rib-1.5.1/lib/rib/api.rb:30:in `catch'
  D:/Bitnami/rubystack-2.2.5-3/ruby/lib/ruby/gems/2.2.0/gems/rib-1.5.1/lib/rib/api.rb:30:in `in_loop'
  D:/Bitnami/rubystack-2.2.5-3/ruby/lib/ruby/gems/2.2.0/gems/rib-1.5.1/lib/rib/shell.rb:51:in `loop'
  D:/Bitnami/rubystack-2.2.5-3/ruby/lib/ruby/gems/2.2.0/gems/rib-1.5.1/lib/rib/runner.rb:82:in `loop'
  D:/Bitnami/rubystack-2.2.5-3/ruby/lib/ruby/gems/2.2.0/gems/rib-1.5.1/lib/rib/runner.rb:77:in `run'
  D:/Bitnami/rubystack-2.2.5-3/ruby/lib/ruby/gems/2.2.0/gems/rib-1.5.1/bin/rib:5:in `<top (required)>'
  D:/Bitnami/rubystack-2.2.5-3/ruby/lib/ruby/gems/2.2.0/bin/rib:22:in `load'
  D:/Bitnami/rubystack-2.2.5-3/ruby/lib/ruby/gems/2.2.0/bin/rib:22:in `<main>'
>>

**Comment by godfat** [comment]
We have two ways to fix this, one would be updating the regular expression in `lib/rib/core/multiline.rb`. This could be annoying because I don't know if this would break the other stuffs, and we'll also need to take care of JRuby and Rubinius, which are giving different error messages.

Alternatively, we could just detect if the input ends with `'\'`, and if that's the case, just consider it multi-line.

I would try the latter.

**Comment by godfat** [comment]
I just released 1.5.3 which includes support for this
